[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy", "rust-src", "llvm-tools-preview"]
profile = "minimal"
targets = ["x86_64-unknown-linux-gnu", "bpfel-unknown-none"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.bpfel-unknown-none]
linker = "clang"