[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src", "rust-analysis", "rust-docs"]
profile = "minimal"
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"